#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -ge 5 -a -n "$OVERLAY" ]
	then
#		echo "FACTORY RESET" > /dev/console
#		jffs2reset -y && reboot &
		echo "RESTORE factory SETTINGS" > /dev/console
		firstboot -y && reboot &
	fi
;;
esac

return 0
